version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/aws-ecr-build-push"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/aws-eks-helm-deploy"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/aws-serverless-deploy"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/ghcr-build-push"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/git-crypt-unlock"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/helm-lint"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/local-container-build"
    schedule:
      interval: "weekly"
