name: 'Local container build'
description: 'Build a container image locally for use during the action with GHA caching.'
author: 'XIP Online Applications'

branding:
    icon: 'code'
    color: 'blue'

inputs:
    repository:
        description: 'The repository to apply to the container.'
        default: 'local/container-build'
    tag:
        description: 'The tag to apply to the container.'
        default: 'latest'
    context:
        description: 'The context to build the container from.'
        default: '.'
    dockerfile:
        description: 'The Dockerfile to use in the build.'
        default: 'Dockerfile'
    build-args:
        description: 'List of build-time variables.'
        default: ''
    target:
        description: 'The target to use in the build.'
        required: false
    platforms:
        description: 'The comma separated list of platforms to build the container for.'
        default: 'linux/amd64'

outputs:
    repository:
        value: ${{ inputs.repository }}
        description: 'The repository.'
    tag:
        value: ${{ inputs.tag }}
        description: 'The tag.'
    image:
        value: ${{ inputs.repository }}:${{ inputs.tag }}
        description: 'The full image with tag.'

runs:
    using: 'composite'
    steps:
        -   name: Set up [qemu-user-static]
            uses: awalsh128/cache-apt-pkgs-action@latest
            with:
                packages: qemu-user-static

        -   name: Build and push
            shell: bash
            run: |
                platforms=(${{ inputs.platforms }})
                platform_args=""
                for platform in "${platforms[@]}"; do
                    platform_args+="--platform $platform "
                done

                build_args=(${{ inputs.build-args }})
                build_args_str=""
                for arg in "${build_args[@]}"; do
                    build_args_str+="--build-arg $arg "
                done

                buildah build \
                    $platform_args \
                    --tag ${{ steps.login-ecr.outputs.registry }}/${{ inputs.repository }}:${{ inputs.tag }} \
                    --cache-from ${{ steps.login-ecr.outputs.registry }}/${{ inputs.repository }} \
                    --layers \
                    --cache-to ${{ steps.login-ecr.outputs.registry }}/${{ inputs.repository }} \
                    $build_args_str \
                    --target ${{ inputs.target }} \
                    --file ${{ inputs.dockerfile }} \
                    ${{ inputs.context }}
                buildah push ${{ steps.login-ecr.outputs.registry }}/${{ inputs.repository }}:${{ inputs.tag }}
