name: 'Git-crypt unlock'
description: 'Unlock a git-crypt repository.'
author: 'XIP Online Applications'

branding:
    icon: 'unlock'
    color: 'blue'

inputs:
    git-crypt-key:
        description: 'The base64 encoded git-crypt decryption key'
        required: true

runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.git-crypt-key }}
