name: Build & push container to ECR

on:
    workflow_call:
        inputs:
            environment:
                type: string
                description: 'The environment to build the container for.'
                required: true
            repository:
                type: string
                description: 'The repository name to push the image to.'
                required: true
            tag:
                type: string
                description: 'The tag to apply to the container.'
                required: true
            aws-role-arn:
                type: string
                description: 'The AWS role to assume and perform AWS actions with.'
                required: true
            aws-region:
                type: string
                description: 'The AWS region to push the image to.'
                required: true
            aws-session-name:
                type: string
                description: 'The AWS session name to use when assuming the AWS role.'
                default: 'xip-gha-ecr-build-push'
            context:
                type: string
                description: 'The context to build the container from.'
                default: '.'
            dockerfile:
                type: string
                description: 'The Dockerfile to use in the build.'
                default: 'Dockerfile'
            build-args:
                type: string
                description: 'List of build-time variables.'
                default: ''
            platforms:
                type: string
                description: 'The comma separated list of platforms to build the container for.'
                default: 'linux/amd64'
        secrets:
            COMPOSER_AUTH_TOKEN:
                description: 'The GitHub token to use for composer auth.'
                required: false

permissions:
    contents: read
    id-token: write

jobs:
    job:
        name: Build and push container
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v3
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            -   name: Configure AWS Credentials
                uses: aws-actions/configure-aws-credentials@v4
                with:
                    aws-region: ${{ inputs.aws-region }}
                    role-to-assume: ${{ inputs.aws-role-arn }}
                    role-session-name: ${{ inputs.aws-session-name }}

            -   name: Login to Amazon ECR
                id: login-ecr
                uses: aws-actions/amazon-ecr-login@v2

            -   name: Build and push
                uses: docker/build-push-action@v5
                with:
                    context: ${{ inputs.context }}
                    file: ${{ inputs.dockerfile }}
                    push: true
                    tags: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.repository }}:${{ inputs.tag }}
                    build-args: |-
                        ${{ secrets.COMPOSER_AUTH_TOKEN != '' && format('COMPOSER_AUTH=\'{"github-oauth": {"github.com": "{{0}}"} }\'', secrets.COMPOSER_AUTH_TOKEN) || '' }}
                        ${{ inputs.build-args }}
                    platforms: ${{ inputs.platforms }}
                    cache-from: type=gha
                    cache-to: type=gha,mode=max
