name: Lint helm deployment

on:
    workflow_call:
        inputs:
            environment:
                type: string
                description: 'The environment to build the container for.'
                required: true
            tag:
                type: string
                description: 'The tag to use during the deployment.'
                default: 'latest'
            command:
                type: string
                description: 'The command to trigger the deployment. You can use two replacements: {0} = environment, {1} = tag.'
                required: true
            helm-version:
                type: string
                description: 'The helm version to install.'
                default: 'latest'
        secrets:
            git-crypt-key:
                required: false
                description: 'The base64 encoded git-crypt decryption key'

jobs:
    job:
        name: Lint ${{ inputs.environment }}
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Install packages
                run: |
                    sudo apt update
                    sudo apt install -y jq git-crypt

            -   name: Install helm
                uses: azure/setup-helm@v3
                with:
                    version: ${{ inputs.helm-version }}
                    token: ${{ secrets.GITHUB_TOKEN }}

            -   name: Decrypt with git-crypt
                run: |
                    KEY=${{ secrets.git-crypt-key }}
                    if [ ! -z "$KEY" ]; then
                        echo $KEY | base64 -d > /tmp/git-crypt.key
                        git-crypt unlock /tmp/git-crypt.key
                        rm /tmp/git-crypt.key
                    fi

            - name: Lint helm chart
              run: ${{ format(inputs.command, inputs.environment, inputs.tag) }}
